#cloud-config
autoinstall:
  version: 1

  source:  # on the Ubuntu Server ISO, install with the minimal source
    id: ubuntu-server-minimal

  identity:
    hostname: broker-vm
    username: brokeradmin
    # Generar contraseña con mkpasswd -m sha-512. 
    # La contraseña es "brokeradmin" y se puede cambiar después de la instalación.
    password: "$6$TNxrzr58RzVi1goJ$D9SlN7rxxDFmiKm0ERbKax2YCf8PJqoOVdrLt/.Mcsw4a1tQ0n1dYc08lD4C5RLhw2EsoHugP/KMqt49ZczXT0"
  
  # Setup network con DHCP para todas las interfaces de red
  network:
    version: 2
    ethernets:
      all-eth:
        match:
          name: en*
        dhcp4: true
        dhcp6: true

  refresh-installer:
    update: no

  locale: es_CL.UTF-8
  timezone: America/Santiago

  keyboard:
    layout: latam

  user-data:
    broker:
      setup_mode: automatic # crear archivos de configuracion y contraseñas de mosquitto de forma automatica

  ssh:
    install_server: true
    allow-pw: true
    allow-public-key: true

  apt:
    update: true

  packages:
    - python3-full
    - python3-pip
    - python3-venv
    - avahi-daemon
    - net-tools
    - whoami

    # Bloque: sistema base
    - git

    # Broker
    - mosquitto
    - mosquitto-clients

  # ----------------------------------------------------------
  # SECCION: CONFIGURACION FINAL
  # ----------------------------------------------------------
  late-commands: # broker-vm.local -> IP
    - curtin in-target -- systemctl enable avahi-daemon --now

    # ejecutar script de configuracion de mosquitto
    - curtin in-target -- systemctl enable mosquitto --now
    - curtin in-target -- systemctl enable ssh --now

    # instalar repositorio de simulador-solarismonitor
    - curtin in-target -- su - brokeradmin -c 'git clone https://github.com/vq00001/Simulador-SolarisMonitor ~/Simulador-SolarisMonitor'
    - curtin in-target -- python3 /home/brokeradmin/Simulador-SolarisMonitor/config/mosquitto_setup.py --mode automatic
    
      # mover archivos de configuracion a /etc/mosquitto
    - curtin in-target -- mv /home/brokeradmin/Simulador-SolarisMonitor/virtual_machine_configs/broker_vm/mosquitto.conf /etc/mosquitto
    - curtin in-target -- mv /home/brokeradmin/Simulador-SolarisMonitor/virtual_machine_configs/broker_vm/acl /etc/mosquitto
    - curtin in-target -- chown mosquitto:mosquitto /etc/mosquitto/mosquitto.conf
    - curtin in-target -- chown mosquitto:mosquitto /etc/mosquitto/acl

    - curtin in-target -- systemctl restart mosquitto
    - curtin in-target -- echo "Configuración de mosquitto finalizada"

    # configurar red para simular condiciones de red
    # reconocer la interfaz de red predeterminada y aplicar limitaciones de ancho de banda y latencia
    - |
      curtin in-target -- bash -c '
        BANDWIDTH=54mbit
        DELAY=2ms
        LOSS=0.1%

        IFACE=$(ip route | awk "/default/ {print \$5}")             
        tc qdisc add dev "$IFACE" root netem \
          rate "$BANDWIDTH" \
          delay "$DELAY"\
          loss "$LOSS"
      '

    - curtin in-target -- echo "Configuración de red finalizada"