#cloud-config
autoinstall:
  version: 1

  source:  # on the Ubuntu Server ISO, install with the minimal source
    id: ubuntu-server-minimal

  identity:
    hostname: broker-vm
    username: brokeradmin
    # Generar contraseña con mkpasswd -m sha-512
    password: "password"
  
  # Setup network con DHCP para todas las interfaces de red
  network:
    version: 2
    ethernets:
      all-eth:
        match:
          name: en*
        dhcp4: true
        dhcp6: true

  refresh-installer:
    update: no

  locale: es_CL.UTF-8
  timezone: America/Santiago

  keyboard:
    layout: latam

  user-data:
    broker:
      setup_mode: automatic # crear archivos de configuracion y contraseñas de mosquitto de forma automatica

  ssh:
    install_server: true
    allow-pw: true
    allow-public-key: true

  apt:
    update: true

  packages:
    - python3-full
    - python3-pip
    - python3-venv
    - avahi-daemon

    # Bloque: sistema base
    - git

    # Broker
    - mosquitto
    - mosquitto-clients

    # Base de datos
    - postgresql
    - postgresql-client

  # ----------------------------------------------------------
  # SECCION: CONFIGURACION FINAL
  # ----------------------------------------------------------
  late-commands: # broker-vm.local -> IP
    - curtin in target -- apt update
    - curtin in-target -- systemctl enable avahi-daemon --now

    # ejecutar script de configuracion de mosquitto
    - curtin in-target -- systemctl enable mosquitto --now
    - curtin in-target -- systemctl enable ssh --now

    # instalar repositorio de simulador-solarismonitor
    - curtin in-target -- su - brokeradmin -c 'git clone https://github.com/vq00001/Simulador-SolarisMonitor ~/Simulador-SolarisMonitor'
    - curtin in-target -- python3 /home/brokeradmin/Simulador-SolarisMonitor/config/mosquitto_setup.py --mode automatic
    
    - curtin in-target -- echo "Configuración de mosquitto finalizada"

    # Configuraciones de la base de datos 
    - curtin in-target -- systemctl enable postgresql --now
    #Crea el usuario y lo guarda en la variable de entorno DATABASE_URL
    - curtin in-target -- sudo -u postgres psql -c "CREATE USER solaris WITH PASSWORD 'solaris123';"
    - curtin in-target -- bash -c 'echo "DATABASE_URL=postgresql+asyncpg://solaris:solaris123@localhost/solarismonitor" >> /etc/environment'
    - curtin in-target -- bash -c 'echo "DATABASE_URL_SYNC=postgresql://solaris:solaris123@localhost/solarismonitor" >> /etc/environment'
    # Crea la base de datos solarismonitor y le asigna el usuario solaris como propietario
    - curtin in-target -- sudo -u postgres createdb -O solaris solarismonitor
    #Instala dependencias del server
    - curtin in-target -- su - brokeradmin -c 'python3 -m venv ~/venv'
    - curtin in-target -- su - brokeradmin -c '~/venv/bin/pip install -r ~/Simulador-SolarisMonitor/requirements.txt'
    